# -*- coding: utf-8 -*-
"""PhotonSimLinkMain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HmRazebET-YtHHMVgwiEzNAmdcY0dvkY
"""

# 1. Install required libraries
# NOTE: this !pip line only works inside a Colab/Jupyter cell. If you ever run this
# as a standalone `python main.py` script (per your README's local/GCP instructions),
# delete this line and use `pip install -r requirements.txt` instead.
!pip install -q -U groq gradio pmcx numpy matplotlib

import os
import sys
import zipfile
import json
import re
import warnings
import io
import base64
import numpy as np
import matplotlib.pyplot as plt
import gradio as gr
import pmcx
from groq import Groq

try:
    from google.colab import userdata
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
except ImportError:
    # not running in Colab (local machine / GCP VM) -- fall back to env var
    GROQ_API_KEY = os.environ.get('GROQ_API_KEY')

warnings.filterwarnings('ignore', category=SyntaxWarning)

# --- 0. Auto-Unpack pVTS Package & Setup Resources ---
if os.path.exists('pVTS.zip'):
    with zipfile.ZipFile('pVTS.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
    print("Successfully extracted pVTS package from pVTS.zip!")
elif os.path.exists('pVTS/pVTS.zip'):
    with zipfile.ZipFile('pVTS/pVTS.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
    print("Successfully extracted pVTS package from pVTS/pVTS.zip!")

os.makedirs("resources", exist_ok=True)

# --- 0. Defensive patch: force the SpectralDatabase import into ChromophoreAbsorber.py ---
# pVTS.zip may still contain an older copy of this file that calls
# SpectralDatabase.get_extinction_coefficient(...) without importing
# SpectralDatabase first -- this silently raises NameError at runtime and
# routes every request through the math fallback with no visible error in
# the pipeline output (resolve_optical_properties() catches and swallows it).
# Since the zip gets re-extracted fresh on every run, any earlier manual fix
# to the extracted file gets overwritten -- so this patch runs every time,
# after extraction, to guarantee the fix survives regardless of what's
# actually packaged inside pVTS.zip.
_chrom_absorber_path = os.path.join("pVTS", "ChromophoreAbsorber.py")
if os.path.exists(_chrom_absorber_path):
    with open(_chrom_absorber_path, "r") as f:
        _chrom_absorber_content = f.read()
    if "from .SpectralDatabase import SpectralDatabase" not in _chrom_absorber_content:
        with open(_chrom_absorber_path, "w") as f:
            f.write("from .SpectralDatabase import SpectralDatabase\n" + _chrom_absorber_content)
        print("[PATCH] Added missing 'from .SpectralDatabase import SpectralDatabase' to ChromophoreAbsorber.py")

# --- 0. Import pVTS as a real Python package (NOT file-injection) ---
# Previously this used importlib.util.spec_from_file_location() to load each
# pVTS file as an isolated module. That approach broke every relative import
# inside the pVTS package (Tissue.py's `from .ChromophoreAbsorber import ...`,
# etc.) and was the root cause of most of the "duplicate SpectralDatabase
# class" / NameError debugging in this project. Importing pVTS as a real
# package lets Python resolve those relative imports normally.
pVTS_parent_dir = "/content" if os.path.exists("/content/pVTS") else "."
if pVTS_parent_dir not in sys.path:
    sys.path.insert(0, pVTS_parent_dir)

# Force a clean reload of the pVTS package every time this cell runs.
# Without this, re-running this cell after editing a pVTS file (e.g. via
# %%writefile in another cell) would keep using the OLD cached module --
# the exact "stale code" problem that caused repeated confusing errors
# during development. This guarantees each run picks up current files.
for mod_name in list(sys.modules.keys()):
    if mod_name == "pVTS" or mod_name.startswith("pVTS."):
        del sys.modules[mod_name]

pVTS_loaded_successfully = False
SpectralDatabase = None
load_vts_resources_columnar = None
Tissue = None
TissueType = None

try:
    from pVTS.SpectralDatabase import SpectralDatabase
    from pVTS.SpectralLoader import load_vts_resources_columnar
    from pVTS.Tissue import Tissue, TissueType
    pVTS_loaded_successfully = True
    print("[SUCCESS] pVTS package imported successfully!")
except Exception as e:
    print(f"[NOTE] pVTS files not found or failed to import. Will rely on math fallback: {e}")

# Load real spectral data if available.
# NOTE: the loader looks for "Spectra.txt", not "OpticalDatabase.txt" -- an
# earlier version of this check looked for the wrong filename and silently
# never loaded real data as a result, even when pVTS imported successfully.
#
# unit_overrides below corrects a known mislabeled header in this specific
# Spectra.txt file: it declares "1/(mm*uM)" but the actual raw values are in
# 1/(cm*mM), off by a factor of 10,000. If you replace this file with one
# that has correctly labeled units, remove this override.
if pVTS_loaded_successfully and os.path.exists(os.path.join("resources", "Spectra.txt")):
    try:
        load_vts_resources_columnar(
            SpectralDatabase,
            "resources",
            scale_overrides={"HbO2": 1 / 10000, "Hb": 1 / 10000},
        )
        print("pVTS spectral resources successfully loaded into memory!")
    except Exception as e:
        print(f"[NOTE] Spectral resource loading failed: {e}")
else:
    if pVTS_loaded_successfully:
        print("[NOTE] resources/Spectra.txt not found -- pVTS will have no real spectral data to look up.")

# Core Biophotonics Calculation Functions (fallback path)
def calculate_mua_beer_lambert(wavelength_nm, hb_conc_uM=30.0, hbo2_conc_uM=70.0):
    eps_hb_uM = (32000.0 * np.exp(-0.004 * wavelength_nm) + 500.0) * 1e-6
    eps_hbo2_uM = (15000.0 * np.exp(-0.002 * wavelength_nm) + 200.0) * 1e-6
    mua_cm_inv = 2.303 * ((eps_hb_uM * hb_conc_uM) + (eps_hbo2_uM * hbo2_conc_uM))
    return float(mua_cm_inv / 10.0)

def calculate_mus_from_wavelength(wavelength_nm):
    a_mie = 200.0
    b_mie = 1.5
    ref_wavelength = 500.0
    mus_cm_inv = a_mie * ((wavelength_nm / ref_wavelength) ** (-b_mie))
    return float(mus_cm_inv / 10.0)

# Optical Property Resolver (pVTS with Math Fallback)
def resolve_optical_properties(wavelength_nm, tissue_type=None):
    """
    Attempts to pull properties from the real pVTS Tissue/chromophore/scatterer
    chain first. If pVTS isn't loaded, fails, or the database lookup errors,
    falls back to the Beer-Lambert/power-law math approximation.

    NOTE: previously this called `SpectralDatabase.get_properties(wavelength_nm)`,
    a method that never existed on SpectralDatabase (it only has
    get_extinction_coefficient/get_spectrum_value/register_spectrum/get_spectrum).
    That call always raised AttributeError and silently fell through to the
    math fallback -- meaning pVTS was NEVER actually used, regardless of
    whether the rest of the pVTS package worked correctly. This is now wired
    to the real Tissue class instead.

    Returns physical mus (not reduced mus') since that's what pmcx's
    cfg.prop = [mua, mus, g, n] convention expects.
    """
    global pVTS_loaded_successfully

    if tissue_type is None and TissueType is not None:
        tissue_type = TissueType.Skin

    if pVTS_loaded_successfully and Tissue is not None:
        try:
            tissue = Tissue(tissue_type=tissue_type)
            mua = tissue.get_mua(wavelength_nm)
            mus = tissue.get_mus(wavelength_nm)   # physical mus, NOT musp -- pmcx needs this one
            g = tissue.get_g(wavelength_nm)
            n = tissue.n
            return [float(mua), float(mus), float(g), float(n)], "pVTS Database Lookup (Primary C# Port)"
        except Exception as pvts_err:
            print(f"[pVTS resolver failed]: {pvts_err}")

    # Fallback Triggered Explicitly
    mua = calculate_mua_beer_lambert(wavelength_nm)
    mus = calculate_mus_from_wavelength(wavelength_nm)
    return [mua, mus, 0.90, 1.40], "⚠️ FALLBACK ACTIVATED: Beer-Lambert & Mie Scattering Math Engine"

# --- 0. Auto-Create Required Markdown Files ---
with open("skill_params.md", "w") as f:
   f.write(r"""# SKILL: PMCX Simulation Parameter Translator & Interpreter
## Role
You are an expert biophotonics assistant. Your task is to translate plain English clinical scenarios into valid PMCX simulation parameters, parse requested wavelengths or properties, perform automated constraint validation, and interpret simulation outputs.
## Workflow
1. **Translation**: Parse plain English input into a `simulation_config` JSON, specifically extracting target wavelength parameters if mentioned.
2. **Verification (Gatekeeper)**: Validate parameters against physical constraints. If invalid, reject the request and output an error log.
3. **Simulation**: Execute the `pmcx.mcxlab()` pipeline natively in-memory.
4. **Interpretation**: Analyze output and assign a confidence score.

## Simulation Parameters Configuration (Must be included in JSON)
* **cfg.nphoton**: Total number of photons (Default: 1,000,000).
* **cfg.vol**: 3D array mapping integers to tissue types (Backend handled; NEVER define or mutate this in output).
* **cfg.prop**: Matrix of `[mua, mus, g, n]` for each tissue type.
* **cfg.srcpos**: Source 3D coordinates `[x, y, z]`.
* **cfg.srcdir**: Source launch direction vector `[nx, ny, nz]` (Default: [0, 0, 1]).
* **cfg.tstart**: Simulation starting time (Default: 0).
* **cfg.tend**: Simulation ending time in seconds (Default: 5e-9).
* **cfg.tstep**: Time-gate step size in seconds (Default: 5e-9).

## Verification Rules (Hard Constraints)
Flag as `Constraint Check: False` if any of the following are met:
* **Absorption (`mua`)**: `mua < 0` or `mua > 5.0`.
* **Scattering (`mus`)**: `mus <= 0` or `mus > 500`.
* **Anisotropy (`g`)**: `g < 0` or `g >= 1`.
* **Refractive Index (`n`)**: `n < 1.0` or `n > 1.6`.
* **Source**: `srcpos` or `srcdir` coordinates fall outside valid grid/physical vectors.

## Negative Constraints (What NOT to do)
* **NEVER output the `cfg.vol` array**: It is a backend object. Generating it will cause memory errors.
* **NEVER approximate values**: Use the fixed constants provided (`5e-9`) rather than "roughly" or "approximately" defined values.
* **NEVER output anything else than JSON**: ONLY output raw JSON. NO MARKDOWN, NO INTRO TEXT, NO CONVERSATIONAL FILLER.

## Output Format
Your response must be a JSON object containing:
- `target_wavelength`: Float value of the wavelength extracted from the text (or 850.0 default).
- `config`: { "nphoton", "prop", "srcpos", "srcdir", "tstart", "tend", "tstep" }
- `confidence_report`: { "score", "logic", "constraint_check" }""")

# --- 2. Setup ---
client = Groq(api_key=GROQ_API_KEY)

with open('skill_params.md', 'r') as f:
   params_context = f.read()

# 3. Deterministic Verification Script
def verify_parameters(params: dict):
    errors = []
    cfg = params.get('config', {})
    prop = cfg.get('prop', [])

    if not cfg or 'nphoton' not in cfg:
        errors.append("The simulation configuration structure is missing the mandatory 'nphoton' execution key.")
        return False, "\n".join(errors)

    for idx, layer in enumerate(prop):
        if len(layer) != 4:
            errors.append(f"Layer {idx} is invalid. Expected 4 metrics [mua, mus, g, n], received {len(layer)}.")
            continue

        mua, mus, g, n = layer[0], layer[1], layer[2], layer[3]

        if idx == 0 and mua == 0 and mus == 0:
            continue

        if mua < 0 or mua > 5.0:
            errors.append(f"Layer {idx} Absorption (mua={mua}) violates constraints (Must be 0.0 to 5.0).")
        if mus <= 0 or mus > 500:
            errors.append(f"Layer {idx} Scattering (mus={mus}) violates constraints (Must be 0.0 to 500).")
        if g < 0 or g >= 1:
            errors.append(f"Layer {idx} Anisotropy (g={g}) violates constraints (Must be 0.0 to <1.0).")
        if n < 1.0 or n > 1.6:
            errors.append(f"Layer {idx} Refractive Index (n={n}) violates constraints (Must be 1.0 to 1.6).")

    if errors:
        return False, "\n".join(errors)
    return True, "Parameters verified successfully."

# 4. The Pipeline
# 1. Install required libraries
# NOTE: this !pip line only works inside a Colab/Jupyter cell. If you ever run this
# as a standalone `python main.py` script (per your README's local/GCP instructions),
# delete this line and use `pip install -r requirements.txt` instead.
!pip install -q -U groq gradio pmcx numpy matplotlib

import os
import sys
import zipfile
import json
import re
import warnings
import io
import base64
import numpy as np
import matplotlib.pyplot as plt
import gradio as gr
import pmcx
from groq import Groq

try:
    from google.colab import userdata
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
except ImportError:
    # not running in Colab (local machine / GCP VM) -- fall back to env var
    GROQ_API_KEY = os.environ.get('GROQ_API_KEY')

warnings.filterwarnings('ignore', category=SyntaxWarning)

# --- 0. Auto-Unpack pVTS Package & Setup Resources ---
if os.path.exists('pVTS.zip'):
    with zipfile.ZipFile('pVTS.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
    print("Successfully extracted pVTS package from pVTS.zip!")
elif os.path.exists('pVTS/pVTS.zip'):
    with zipfile.ZipFile('pVTS/pVTS.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
    print("Successfully extracted pVTS package from pVTS/pVTS.zip!")

os.makedirs("resources", exist_ok=True)

# --- 0. Defensive patch: force the SpectralDatabase import into ChromophoreAbsorber.py ---
# pVTS.zip may still contain an older copy of this file that calls
# SpectralDatabase.get_extinction_coefficient(...) without importing
# SpectralDatabase first -- this silently raises NameError at runtime and
# routes every request through the math fallback with no visible error in
# the pipeline output (resolve_optical_properties() catches and swallows it).
# Since the zip gets re-extracted fresh on every run, any earlier manual fix
# to the extracted file gets overwritten -- so this patch runs every time,
# after extraction, to guarantee the fix survives regardless of what's
# actually packaged inside pVTS.zip.
_chrom_absorber_path = os.path.join("pVTS", "ChromophoreAbsorber.py")
if os.path.exists(_chrom_absorber_path):
    with open(_chrom_absorber_path, "r") as f:
        _chrom_absorber_content = f.read()
    if "from .SpectralDatabase import SpectralDatabase" not in _chrom_absorber_content:
        with open(_chrom_absorber_path, "w") as f:
            f.write("from .SpectralDatabase import SpectralDatabase\n" + _chrom_absorber_content)
        print("[PATCH] Added missing 'from .SpectralDatabase import SpectralDatabase' to ChromophoreAbsorber.py")

# --- 0. Import pVTS as a real Python package (NOT file-injection) ---
# Previously this used importlib.util.spec_from_file_location() to load each
# pVTS file as an isolated module. That approach broke every relative import
# inside the pVTS package (Tissue.py's `from .ChromophoreAbsorber import ...`,
# etc.) and was the root cause of most of the "duplicate SpectralDatabase
# class" / NameError debugging in this project. Importing pVTS as a real
# package lets Python resolve those relative imports normally.
pVTS_parent_dir = "/content" if os.path.exists("/content/pVTS") else "."
if pVTS_parent_dir not in sys.path:
    sys.path.insert(0, pVTS_parent_dir)

# Force a clean reload of the pVTS package every time this cell runs.
# Without this, re-running this cell after editing a pVTS file (e.g. via
# %%writefile in another cell) would keep using the OLD cached module --
# the exact "stale code" problem that caused repeated confusing errors
# during development. This guarantees each run picks up current files.
for mod_name in list(sys.modules.keys()):
    if mod_name == "pVTS" or mod_name.startswith("pVTS."):
        del sys.modules[mod_name]

pVTS_loaded_successfully = False
SpectralDatabase = None
load_vts_resources_columnar = None
Tissue = None
TissueType = None

try:
    from pVTS.SpectralDatabase import SpectralDatabase
    from pVTS.SpectralLoader import load_vts_resources_columnar
    from pVTS.Tissue import Tissue, TissueType
    pVTS_loaded_successfully = True
    print("[SUCCESS] pVTS package imported successfully!")
except Exception as e:
    print(f"[NOTE] pVTS files not found or failed to import. Will rely on math fallback: {e}")

# Load real spectral data if available.
# NOTE: the loader looks for "Spectra.txt", not "OpticalDatabase.txt" -- an
# earlier version of this check looked for the wrong filename and silently
# never loaded real data as a result, even when pVTS imported successfully.
#
# unit_overrides below corrects a known mislabeled header in this specific
# Spectra.txt file: it declares "1/(mm*uM)" but the actual raw values are in
# 1/(cm*mM), off by a factor of 10,000. If you replace this file with one
# that has correctly labeled units, remove this override.
if pVTS_loaded_successfully and os.path.exists(os.path.join("resources", "Spectra.txt")):
    try:
        load_vts_resources_columnar(
            SpectralDatabase,
            "resources",
            scale_overrides={"HbO2": 1 / 10000, "Hb": 1 / 10000},
        )
        print("pVTS spectral resources successfully loaded into memory!")
    except Exception as e:
        print(f"[NOTE] Spectral resource loading failed: {e}")
else:
    if pVTS_loaded_successfully:
        print("[NOTE] resources/Spectra.txt not found -- pVTS will have no real spectral data to look up.")

# Core Biophotonics Calculation Functions (fallback path)
def calculate_mua_beer_lambert(wavelength_nm, hb_conc_uM=30.0, hbo2_conc_uM=70.0):
    eps_hb_uM = (32000.0 * np.exp(-0.004 * wavelength_nm) + 500.0) * 1e-6
    eps_hbo2_uM = (15000.0 * np.exp(-0.002 * wavelength_nm) + 200.0) * 1e-6
    mua_cm_inv = 2.303 * ((eps_hb_uM * hb_conc_uM) + (eps_hbo2_uM * hbo2_conc_uM))
    return float(mua_cm_inv / 10.0)

def calculate_mus_from_wavelength(wavelength_nm):
    a_mie = 200.0
    b_mie = 1.5
    ref_wavelength = 500.0
    mus_cm_inv = a_mie * ((wavelength_nm / ref_wavelength) ** (-b_mie))
    return float(mus_cm_inv / 10.0)

# Optical Property Resolver (pVTS with Math Fallback)
def resolve_optical_properties(wavelength_nm, tissue_type=None):
    """
    Attempts to pull properties from the real pVTS Tissue/chromophore/scatterer
    chain first. If pVTS isn't loaded, fails, or the database lookup errors,
    falls back to the Beer-Lambert/power-law math approximation.

    NOTE: previously this called `SpectralDatabase.get_properties(wavelength_nm)`,
    a method that never existed on SpectralDatabase (it only has
    get_extinction_coefficient/get_spectrum_value/register_spectrum/get_spectrum).
    That call always raised AttributeError and silently fell through to the
    math fallback -- meaning pVTS was NEVER actually used, regardless of
    whether the rest of the pVTS package worked correctly. This is now wired
    to the real Tissue class instead.

    Returns physical mus (not reduced mus') since that's what pmcx's
    cfg.prop = [mua, mus, g, n] convention expects.
    """
    global pVTS_loaded_successfully

    if tissue_type is None and TissueType is not None:
        tissue_type = TissueType.Skin

    if pVTS_loaded_successfully and Tissue is not None:
        try:
            tissue = Tissue(tissue_type=tissue_type)
            mua = tissue.get_mua(wavelength_nm)
            mus = tissue.get_mus(wavelength_nm)   # physical mus, NOT musp -- pmcx needs this one
            g = tissue.get_g(wavelength_nm)
            n = tissue.n
            return [float(mua), float(mus), float(g), float(n)], "pVTS Database Lookup (Primary C# Port)"
        except Exception as pvts_err:
            print(f"[pVTS resolver failed]: {pvts_err}")

    # Fallback Triggered Explicitly
    mua = calculate_mua_beer_lambert(wavelength_nm)
    mus = calculate_mus_from_wavelength(wavelength_nm)
    return [mua, mus, 0.90, 1.40], "⚠️ FALLBACK ACTIVATED: Beer-Lambert & Mie Scattering Math Engine"

# --- 0. Auto-Create Required Markdown Files ---
with open("skill_params.md", "w") as f:
   f.write(r"""# SKILL: PMCX Simulation Parameter Translator & Interpreter
## Role
You are an expert biophotonics assistant. Your task is to translate plain English clinical scenarios into valid PMCX simulation parameters, parse requested wavelengths or properties, perform automated constraint validation, and interpret simulation outputs.
## Workflow
1. **Translation**: Parse plain English input into a `simulation_config` JSON, specifically extracting target wavelength parameters if mentioned.
2. **Verification (Gatekeeper)**: Validate parameters against physical constraints. If invalid, reject the request and output an error log.
3. **Simulation**: Execute the `pmcx.mcxlab()` pipeline natively in-memory.
4. **Interpretation**: Analyze output and assign a confidence score.

## Simulation Parameters Configuration (Must be included in JSON)
* **cfg.nphoton**: Total number of photons (Default: 1,000,000).
* **cfg.vol**: 3D array mapping integers to tissue types (Backend handled; NEVER define or mutate this in output).
* **cfg.prop**: Matrix of `[mua, mus, g, n]` for each tissue type.
* **cfg.srcpos**: Source 3D coordinates `[x, y, z]`.
* **cfg.srcdir**: Source launch direction vector `[nx, ny, nz]` (Default: [0, 0, 1]).
* **cfg.tstart**: Simulation starting time (Default: 0).
* **cfg.tend**: Simulation ending time in seconds (Default: 5e-9).
* **cfg.tstep**: Time-gate step size in seconds (Default: 5e-9).

## Verification Rules (Hard Constraints)
Flag as `Constraint Check: False` if any of the following are met:
* **Absorption (`mua`)**: `mua < 0` or `mua > 5.0`.
* **Scattering (`mus`)**: `mus <= 0` or `mus > 500`.
* **Anisotropy (`g`)**: `g < 0` or `g >= 1`.
* **Refractive Index (`n`)**: `n < 1.0` or `n > 1.6`.
* **Source**: `srcpos` or `srcdir` coordinates fall outside valid grid/physical vectors.

## Negative Constraints (What NOT to do)
* **NEVER output the `cfg.vol` array**: It is a backend object. Generating it will cause memory errors.
* **NEVER approximate values**: Use the fixed constants provided (`5e-9`) rather than "roughly" or "approximately" defined values.
* **NEVER output anything else than JSON**: ONLY output raw JSON. NO MARKDOWN, NO INTRO TEXT, NO CONVERSATIONAL FILLER.

## Output Format
Your response must be a JSON object containing:
- `target_wavelength`: Float value of the wavelength extracted from the text (or 850.0 default).
- `config`: { "nphoton", "prop", "srcpos", "srcdir", "tstart", "tend", "tstep" }
- `confidence_report`: { "score", "logic", "constraint_check" }""")

# --- 2. Setup ---
client = Groq(api_key=GROQ_API_KEY)

with open('skill_params.md', 'r') as f:
   params_context = f.read()

# 3. Deterministic Verification Script
def verify_parameters(params: dict):
    errors = []
    cfg = params.get('config', {})
    prop = cfg.get('prop', [])

    if not cfg or 'nphoton' not in cfg:
        errors.append("The simulation configuration structure is missing the mandatory 'nphoton' execution key.")
        return False, "\n".join(errors)

    for idx, layer in enumerate(prop):
        if len(layer) != 4:
            errors.append(f"Layer {idx} is invalid. Expected 4 metrics [mua, mus, g, n], received {len(layer)}.")
            continue

        mua, mus, g, n = layer[0], layer[1], layer[2], layer[3]

        if idx == 0 and mua == 0 and mus == 0:
            continue

        if mua < 0 or mua > 5.0:
            errors.append(f"Layer {idx} Absorption (mua={mua}) violates constraints (Must be 0.0 to 5.0).")
        if mus <= 0 or mus > 500:
            errors.append(f"Layer {idx} Scattering (mus={mus}) violates constraints (Must be 0.0 to 500).")
        if g < 0 or g >= 1:
            errors.append(f"Layer {idx} Anisotropy (g={g}) violates constraints (Must be 0.0 to <1.0).")
        if n < 1.0 or n > 1.6:
            errors.append(f"Layer {idx} Refractive Index (n={n}) violates constraints (Must be 1.0 to 1.6).")

    if errors:
        return False, "\n".join(errors)
    return True, "Parameters verified successfully."

# 4. The Pipeline
def respond(message, history):
    try:
        # Pass 1 System Prompt: Focus solely on parameter extraction and JSON structure validation
        pass1_system_prompt = f"""
You are an expert biophotonics simulation assistant. Read the user's plain English request and translate it into PMCX simulation parameters. Extract any target wavelength mentioned in nanometers (e.g., 750, 800) and place it in 'target_wavelength' (default to 850.0 if none specified).{params_context}

Output ONLY valid JSON containing 'target_wavelength', 'config', and 'confidence_report'.

Use this exact JSON structure:
{{
  "target_wavelength": 850.0,
  "config": {{
    "nphoton": 1000000,
    "tstart": 0.0,
    "tend": 5e-9,
    "tstep": 5e-9,
    "srcpos": [30.0, 30.0, 0.0],
    "srcdir": [0.0, 0.0, 1.0],
    "prop": [[0.0, 0.0, 1.0, 1.0], [0.01, 10.0, 0.9, 1.4]]
  }},
  "confidence_report": {{
    "score": 0.95,
    "logic": "Interpreted plain English simulation scenario and extracted wavelength.",
    "constraint_check": true
  }}
}}"""
        response1 = client.chat.completions.create(
            model="qwen/qwen3.6-27b",
            messages=[
                {"role": "system", "content": pass1_system_prompt},
                {"role": "user", "content": message}
            ],
            response_format={"type": "json_object"}
        )

        raw_content1 = response1.choices[0].message.content.strip()
        if raw_content1.startswith("```"):
            raw_content1 = re.sub(r"^```(?:json)?\s*", "", raw_content1)
            raw_content1 = re.sub(r"\s*```$", "", raw_content1)

        params = json.loads(raw_content1)

    except Exception as e:
        # Keep fallback structurally parallel so it never breaks down-funnel
        params = {
            "target_wavelength": 850.0,
            "config": {"nphoton": 1000000, "srcpos": [30.0, 30.0, 0.0], "srcdir": [0.0, 0.0, 1.0]},
            "confidence_report": {"score": 0.8, "logic": f"Fallback triggered due to parse error: {e}", "constraint_check": True}
        }

    # Step 2: Resolve optical properties using Hybrid Architecture (pVTS -> Math Fallback)
    try:
        extracted_wavelength = float(params.get("target_wavelength", 850.0))
        computed_prop_vector, calculation_source = resolve_optical_properties(extracted_wavelength)
        if 'config' not in params:
            params['config'] = {}
        params['config']['prop'] = [[0.0, 0.0, 1.0, 1.0], computed_prop_vector]
        calculation_note = f"Resolved via {calculation_source} at {extracted_wavelength} nm."
    except Exception as func_err:
        calculation_source = "⚠️ FALLBACK ACTIVATED: Hybrid resolver execution fallback"
        calculation_note = f"⚠️ FALLBACK ACTIVATED: Hybrid resolver execution fallback: {func_err}"
        computed_prop_vector = [0.045, 12.3, 0.90, 1.40]
        if 'config' not in params:
            params['config'] = {}
        params['config']['prop'] = [[0.0, 0.0, 1.0, 1.0], computed_prop_vector]

    is_valid, validation_log = verify_parameters(params)
    if not is_valid:
        return f"[WARNING] Verification Layer Flagged Anomalous Parameters:\n\n{validation_log}\n\nExecution terminated to protect system safety."

    try:
        cfg = {**params['config']}
        cfg['vol'] = np.ones((60, 60, 60), dtype=np.uint8)
        cfg['tstart'] = 0.0
        cfg['tend'] = 5e-9
        cfg['tstep'] = 5e-9

        srcpos_raw = cfg.get('srcpos', [30.0, 30.0, 0.0])
        srcdir_raw = cfg.get('srcdir', [0.0, 0.0, 1.0])
        cfg['srcpos'] = np.array(srcpos_raw, dtype=np.float32)
        cfg['srcdir'] = np.array(srcdir_raw, dtype=np.float32)

        cfg['srcpos'] = np.clip(cfg['srcpos'], 0.0, 59.0)
        cfg['srcpos'][2] = max(0.0, cfg['srcpos'][2])

        target_x = int(np.clip(cfg['srcpos'][0], 0, 59))
        target_y = int(np.clip(cfg['srcpos'][1], 0, 59))

        cfg['prop'] = np.array(cfg['prop'], dtype=np.float32)

        # --- GPU TO MOCK CPU FALLBACK GATE ---
        is_mock_mode = False
        try:
            sim_data = pmcx.mcxlab(cfg)
            flux_matrix = None
            if isinstance(sim_data, dict):
                for key in ['flux', 'Flux', 'fluence', 'Fluence', 'Ed', 'ed']:
                    if key in sim_data and sim_data[key] is not None:
                        flux_matrix = np.array(sim_data[key], dtype=np.float32)
                if flux_matrix is None or not np.any(flux_matrix):
                    for k, v in sim_data.items():
                        if isinstance(v, np.ndarray) and np.any(v):
                            flux_matrix = np.array(v, dtype=np.float32)
                            break
            elif isinstance(sim_data, np.ndarray) and np.any(sim_data):
                flux_matrix = np.array(sim_data, dtype=np.float32)

            if flux_matrix is None or not np.any(flux_matrix):
                raise KeyError("Valid non-zero flux array missing from native hardware returns.")
        except Exception as hardware_error:
            print(f"GPU execution failed, falling back to mock mode: {hardware_error}")
            is_mock_mode = True
            flux_matrix = np.zeros((60, 60, 60, 1), dtype=np.float32)
            for z in range(60):
                flux_matrix[target_x, target_y, z, 0] = 1.4e+08 * np.exp(-0.25 * z)
            noise = np.random.uniform(10, 1000, size=(60, 60, 60, 1)).astype(np.float32)
            flux_matrix += noise

        # --- DATA PROCESSING & BIOMEDICAL TELEMETRY ---
        if flux_matrix is not None:
            print(f"[DIAGNOSTIC] raw flux -- shape: {flux_matrix.shape}, "
                  f"NaN count: {np.isnan(flux_matrix).sum()}, "
                  f"Inf count: {np.isinf(flux_matrix).sum()}, "
                  f"nonzero-finite count: {np.sum(np.isfinite(flux_matrix) & (flux_matrix != 0))}, "
                  f"min/max (finite only): {np.nanmin(flux_matrix[np.isfinite(flux_matrix)]) if np.isfinite(flux_matrix).any() else 'N/A'}"
                  f"/{np.nanmax(flux_matrix[np.isfinite(flux_matrix)]) if np.isfinite(flux_matrix).any() else 'N/A'}")

            flux_matrix = np.nan_to_num(flux_matrix, nan=0.0, posinf=0.0, neginf=0.0)
            max_idx = [int(x) for x in np.unravel_index(np.argmax(flux_matrix), flux_matrix.shape)]
            total_energy = float(np.sum(flux_matrix))
            peak_intensity = float(np.max(flux_matrix))
            active_mua = float(computed_prop_vector[0])

            if flux_matrix.ndim == 4:
                center_beam_z = flux_matrix[target_x, target_y, :, 0]
            elif flux_matrix.ndim == 3:
                center_beam_z = flux_matrix[target_x, target_y, :]
            else:
                center_beam_z = flux_matrix.flatten()

            peak_z_val = np.max(center_beam_z) if len(center_beam_z) > 0 else 0
            if peak_z_val > 0:
                valid_depths = np.where(center_beam_z > (peak_z_val * 0.05))[0]
                true_penetration_voxels = int(valid_depths[-1]) if len(valid_depths) > 0 else 0
            else:
                true_penetration_voxels = 0

        # --- GENERATE DEPTH PROFILE PLOT (INLINE BASE64) ---
        fig, ax = plt.subplots(figsize=(6, 2.5))
        safe_beam_z = np.clip(center_beam_z, a_min=1e-12, a_max=None)
        ax.plot(safe_beam_z, color='#00a8cc', lw=2)
        ax.set_yscale('log')
        ax.set_title(f"Laser Penetration Profile ({extracted_wavelength} nm)", fontsize=10, fontweight='bold')
        ax.set_xlabel("Depth into Skin (mm)", fontsize=9)
        ax.set_ylabel("Light Intensity (Log Scale)", fontsize=9)
        ax.grid(True, which="both", alpha=0.3, linestyle='--')

        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches='tight', dpi=100)
        buf.seek(0)
        img_str = base64.b64encode(buf.read()).decode('utf-8')
        plt.close(fig)
        plot_markdown = f"\n\n### 📈 Laser Penetration & Energy Spread\n![Penetration Curve](data:image/png;base64,{img_str})"

        # --- DUAL-PATH THERMAL FRAMEWORK ---
        THERMAL_DAMAGE_THRESHOLD = 10.0
        if is_mock_mode:
            THERMAL_CALIBRATION_CONSTANT = 9.27
            estimated_delta_t = active_mua * THERMAL_CALIBRATION_CONSTANT
            gpu_status = (
                f"⚠️ WARNING! OFFLINE MOCK MODE ACTIVE (No NVIDIA GPU/CUDA detected! Dynamically scaled via CPU test fixture)\n\n"
                f"* Voxel Flux Array Shape: {flux_matrix.shape}\n"
                f"* Photon Penetration Confirmed: True"
            )
        else:
            total_photons = cfg.get('nphoton', 1000000)
            normalized_intensity = peak_intensity / total_photons
            DENSITY = 1.05
            SPECIFIC_HEAT = 3.6
            estimated_delta_t = (active_mua * normalized_intensity * 15.0) / (DENSITY * SPECIFIC_HEAT)
            gpu_status = (
                f"Native Simulation Complete via Connected Hardware.\n\n"
                f"* NVIDIA GPU Execution time: ~0.2 seconds\n"
                f"* 3D Voxel Flux Array Shape: {flux_matrix.shape}\n"
                f"* Photon Penetration Confirmed: {total_energy > 0}"
            )

        # --- STATUS BANNER ---
        pvts_is_real = "FALLBACK" not in calculation_source
        gpu_is_real = not is_mock_mode

        if pvts_is_real and gpu_is_real:
            status_banner = "🟢 FULLY VERIFIED — real pVTS spectral data + real GPU hardware simulation."
        elif pvts_is_real and not gpu_is_real:
            status_banner = "🟡 PARTIAL — real pVTS spectral data, but GPU simulation is MOCK (no CUDA hardware detected)."
        elif not pvts_is_real and gpu_is_real:
            status_banner = "🟠 PARTIAL — real GPU hardware simulation, but optical properties are PLACEHOLDER (pVTS database not loaded, using generic math approximation)."
        else:
            status_banner = "🔴 UNVERIFIED — both optical properties (pVTS) and GPU simulation are PLACEHOLDER/MOCK. Treat all results as illustrative only."

        confidence_display = (
            f"{params['confidence_report'].get('score')}/1.0" if pvts_is_real else "N/A — placeholder optical data in use, LLM confidence score not meaningful here"
        )
        penetration_text = f"Controlled optical penetration across {true_penetration_voxels} grid layers."
        absorption_text = f"Distributed internal energy deposition peaking at {max_idx} | Peak Intensity: {peak_intensity:.1e}"
        placeholder_caveat = "" if pvts_is_real else " (based on PLACEHOLDER absorption data -- not yet verified against pVTS; re-run once real spectral data is loaded before treating this as a safety finding)"

        if estimated_delta_t >= THERMAL_DAMAGE_THRESHOLD:
            clinical_text = (
                f"⚠️⚠️⚠️ DANGER{placeholder_caveat}! Localized energy density is high enough to induce thermal tissue damage! "
                f"(Calculated dT: {estimated_delta_t:.2f} C). High risk of protein denaturation and localized cell necrosis."
            )
        else:
            clinical_text = (
                f"Standard laser-tissue interaction{placeholder_caveat}. Total Energy: {total_energy:.1e}, Peak Flux: {peak_intensity:.1e}. "
                f"(Calculated dT: {estimated_delta_t:.2f} C). Safe light distribution within normal physiological limits."
            )

        # --- 2ND PASS: AI INTERPRETATION & TELEMETRY SYNTHESIS ---
        pass2_prompt = f"""
        You are an expert biophotonics communicator. Write a brief, simple, 2-3 sentence explanation of how this laser simulation behaved, incorporating the exact telemetry below.

        Telemetry Data:
        - Target Wavelength: {extracted_wavelength} nm
        - Tissue Properties [mua, mus, g, n]: {computed_prop_vector}
        - Penetration Depth: {true_penetration_voxels} grid layers
        - Estimated Temperature Increase (dT): {estimated_delta_t:.2f} °C

        Constraints:
        - Write exclusively in plain, universal English. Non-English characters are strictly banned except the degree symbol, calm down you can use it.
        - Do NOT use academic buzzwords like 'anisotropy', 'ballistic transport', or 'hemoglobin drop-off'.
        - Explicitly mention how the specific wavelength and the resulting temperature change (dT of {estimated_delta_t:.2f} °C) affect the tissue.
        """

        try:
            response2 = client.chat.completions.create(
                model="qwen/qwen3.6-27b",
                messages=[
                    {"role": "system", "content": "You output plain text explanations only. No markdown formatting blocks, no JSON."},
                    {"role": "user", "content": pass2_prompt}
                ]
            )
            ai_essay = response2.choices[0].message.content.strip()
            ai_essay = re.sub(r'<think>.*?</think>', '', ai_essay, flags=re.DOTALL).strip()
        except Exception as e:
            ai_essay = f"AI interpretation generation skipped due to error: {e}"

        response_text = (
            f"{status_banner}\n\n"
            f"Success! Plain English Parsed by LLM & Resolved via Hybrid Architecture.\n\n"
            f"Engine Return Status:\n{gpu_status}\n\n"
            f"Safety & Confidence Report:\n"
            f"* LLM Extracted Wavelength: {extracted_wavelength} nm\n"
            f"* Resolution Source & Note: {calculation_note}\n"
            f"* Constraint Check Pass: {params['confidence_report'].get('constraint_check')}\n"
            f"* Confidence Score: {confidence_display}\n"
            f"* System Logic Validation: {params['confidence_report'].get('logic')}\n"
            f"* Applied Tissue Property Vector [mua, mus, g, n]: {computed_prop_vector}\n\n"
            f"Grounded Engineering Interpretation (Verified Returns):\n"
            f"* Penetration Depth Analysis: {penetration_text} (True Grid Depth: {true_penetration_voxels} voxels)\n"
            f"* Absorption Hotspots: {absorption_text} (True Peak Array Coordinate: {max_idx})\n"
            f"* Thermal & Clinical Significance: {clinical_text}\n\n"
            f"📝 AI INTERPRETATION:\n"
            f"{ai_essay}"
            f"{plot_markdown}"
        )
        return response_text
    except Exception as e:
        return f"Pipeline Error encountered during simulation or processing: {e}"


# --- 5. Launch UI ---
demo = gr.ChatInterface(
    fn=respond,
    title="PhotonSimLink (Hybrid pVTS + Math Fallback)",
    description="Describe your simulation in plain English (e.g., 'Run simulation at 750 nm'); tries the pVTS C# library port first, then explicitly notes if the math fallback activates.",
    textbox=gr.Textbox(
        placeholder="e.g., 'Simulate light transport at 780 nm wavelength'...",
        container=False,
        scale=7
    )
)

if __name__ == "__main__":
    demo.launch(debug=True)